apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: jokefront
build:
  artifacts:
  - image: saphoooo/jokefront
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - deployment.yaml
