apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-master-0
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/redis-data-redis-master-0"
  claimRef:
    name: redis-data-redis-master-0
    namespace: default

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-replicas-0
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/redis-data-redis-replicas-0"
  claimRef:
    name: redis-data-redis-replicas-0
    namespace: default

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: redis-data-redis-replicas-1
# spec:
#   storageClassName: ""
#   capacity:
#     storage: 8Gi
#   accessModes:
#   - ReadWriteOnce
#   hostPath:
#     path: "/data/redis-data-redis-replicas-1"
#   claimRef:
#     name: redis-data-redis-replicas-1
#     namespace: default

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: redis-data-redis-replicas-2
# spec:
#   storageClassName: ""
#   capacity:
#     storage: 8Gi
#   accessModes:
#   - ReadWriteOnce
#   hostPath:
#     path: "/data/redis-data-redis-replicas-2"
#   claimRef:
#     name: redis-data-redis-replicas-2
#     namespace: default